In [33]:
import os
import netCDF4
import numpy as np

In [9]:
os.listdir("demo-data/Meteodata/2021")

['cosmo2_epfl_lakes_20210101.nc',
 'cosmo2_epfl_lakes_20210102.nc',
 'cosmo2_epfl_lakes_20210103.nc',
 'cosmo2_epfl_lakes_20210104.nc']

In [10]:
ncfile = netCDF4.Dataset("demo-data/Meteodata/2021/cosmo2_epfl_lakes_20210101.nc",mode='r',format='NETCDF4_CLASSIC')

In [27]:
ncfile.variables["T_2M"].coordinates.split(" ")

['lon_1', 'lat_1']

In [42]:
ncfile.variables["lat_1"]

<class 'netCDF4._netCDF4.Variable'>
float32 lat_1(y_1, x_1)
    standard_name: latitude
    long_name: latitude
    units: degrees_north
unlimited dimensions: 
current shape = (281, 481)
filling on, default _FillValue of 9.969209968386869e+36 used

In [46]:
coord = [46.35,6.89]

lat = ncfile.variables["lat_1"][:]
lon = ncfile.variables["lon_1"][:]

dist = np.sqrt((lat - coord[0])**2 + (lon - coord[1])**2)
min_dist = np.argwhere(dist == np.min(dist))[0]

In [47]:
min_dist

array([121, 177])

In [54]:
np.array(ncfile.variables["T_2M"][:,min_dist[0],min_dist[1]])-273.15

array([3.6202087, 3.041504 , 2.9580383, 3.2137146, 3.1199646, 3.0161438,
       2.0321655, 1.1964722, 1.023346 , 2.1256714, 2.8822021, 3.4392395,
       3.6230774, 3.5312195, 3.7422485, 3.5785828, 3.2885437, 3.0643616,
       2.464447 , 2.04068  , 2.2368164, 2.0780334, 2.0679016, 1.7994995],
      dtype=float32)

In [56]:
np.array(ncfile.variables["time"][:])

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [64]:
ncfile.variables["RELHUM_2M"]

<class 'netCDF4._netCDF4.Variable'>
float32 RELHUM_2M(time, y_1, x_1)
    units: %
    long_name: 2m relative humidity (with respect to water)
    coordinates: lon_1 lat_1
    grid_mapping: grid_mapping_1
    _FillValue: -3.4028235e+38
unlimited dimensions: time
current shape = (24, 281, 481)
filling on

In [59]:
[] * 4

[]